### ISSUE TITLE
Resource pack help

### ISSUE THREAD

**Issue by machinesmith42** [Linguardium/ItemNbtModels#1]
[VisualEnchantments_32x_Build_2.zip](https://github.com/Linguardium/ItemNbtModels/files/5009412/VisualEnchantments_32x_Build_2.zip)
I am trying to oprt this to your system how would I begin

**Comment by Linguardium** [comment]
thats going to take work but essentially you need to figure out what modifications it looks for, build js evaluation strings for each of those.
ensure the models are proper vanilla format.
move png files to the vanilla location (assets/minecraft/textures/item/)
move json model files to the vanilla location (assets/minecraft/models/item)
inside each item model, you would add an override section if missing
inside the override section you would add the "nbt" override type according to the wiki here.
